<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>CRM.Clients.Infrastructure</AssemblyName>
    <RootNamespace>CRM.Clients.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../CRM.Clients.Domain/CRM.Clients.Domain.csproj" />
    <ProjectReference Include="../CRM.Clients.Application/CRM.Clients.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.0" />
  </ItemGroup>
</Project>
